application: nooksmai
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /fonts
  static_dir: fonts

- url: /images
  static_dir: images

- url: /javascripts
  static_dir: javascripts

- url: /stylesheets
  static_dir: stylesheets

- url: /bootstrap
  static_dir: bootstrap

- url: /textedit
  static_dir: textedit

- url: /back_office
  script: nooksmai.application
  login: admin
  secure: always

- url: /.*
  script: nooksmai.application



libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

