from google.appengine.ext import db

class MovieModel(db.Model):
    original_id = db.IntegerProperty(default=0)
    id = db.IntegerProperty()
    name_en = db.StringProperty()
    name_th = db.StringProperty()
    duration = db.IntegerProperty()
    rate = db.StringProperty()
    image = db.StringProperty()
    release_time_timestamp = db.IntegerProperty()
    thumbnail = db.StringProperty()
    types = db.StringListProperty()
    youtube_url = db.StringProperty()
    comment_count = db.IntegerProperty(default=0)
    create_ = db.DateTimeProperty(auto_now_add=True)
    is_coming_soon = db.IntegerProperty(default=0)
    coming_month_th = db.StringProperty()
    coming_month_en = db.StringProperty()

    detail_synopsis_en = db.TextProperty()
    detail_synopsis_th = db.TextProperty()
    detail_image = db.StringProperty()
    detail_thumbnail = db.StringProperty()
    detail_genre_en = db.StringProperty()
    detail_genre_th = db.StringProperty()      
    detail_director_en = db.StringProperty()
    detail_director_th = db.StringProperty()      
    detail_cast_en = db.StringProperty()
    detail_cast_th = db.StringProperty()
