from google.appengine.ext import db

class MovieModel(db.Model):
    id = db.IntegerProperty()
    ribbon_type = db.IntegerProperty()
    adv_time_timestamp = db.IntegerProperty()
    adv_time_text = db.StringProperty()
    name_en = db.StringProperty()
    name_th = db.StringProperty()
    duration = db.IntegerProperty()
    rate = db.StringProperty()
    rateWarning = db.BooleanProperty()
    image = db.StringProperty()
    release_time_timestamp = db.IntegerProperty()
    release_time_text = db.StringProperty()
    yt_id = db.StringProperty()
    rtsp = db.StringProperty()
    thumbnail = db.StringProperty()
    types = db.StringListProperty()
    cinemas = db.ListProperty(int)
    
    detail_duration = db.IntegerProperty()
    detail_rate = db.StringProperty()
    detail_rateWarning= db.BooleanProperty()        
    detail_timestamp = db.IntegerProperty()
    detail_text = db.StringProperty()
    detail_synopsis_en = db.TextProperty()
    detail_synopsis_th = db.TextProperty()
    detail_image = db.StringProperty()
    detail_yt_id = db.StringProperty()
    detail_rtsp = db.StringProperty()
    detail_thumbnail = db.StringProperty()
    detail_genre_en = db.StringProperty()
    detail_genre_th = db.StringProperty()      
    detail_director_en = db.StringProperty()
    detail_director_th = db.StringProperty()      
    detail_cast_en = db.StringProperty()
    detail_cast_th = db.StringProperty()